# Generated by Django 6.0.2 on 2026-04-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_selectionresult_shortlistedstudent'),
        ('placement_cell', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.companyprofile'),
        ),
    ]
