# Generated by Django 6.0.2 on 2026-02-20 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('cp_name', models.CharField(max_length=150)),
                ('cp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cp_phone', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=150)),
                ('reg_certificate', models.FileField(upload_to='copmpany_certificates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
